import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";
import Profile from "@/components/Profile";
import NavVerticalBar from "@/components/NavVerticalBar";

const libreFranklin = Libre_Franklin({
  variable: "--font-libre-franklin",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/2d05e739d6.js"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`${libreFranklin.className} antialiased text-white `}>
        <div className="flex flex-row justify-center gap-4 p-18">
          <Profile />

          {children}
          <NavVerticalBar />
        </div>
      </body>
    </html>
  );
}
